### PR TITLE
Add pasteConfig which includes <hr>

### PR DESCRIPTION
**Pull request by gajendrajena**
- implement onPaste and pasteConfig for DelimiterWithPaste

[Add pasteConfig which includes `<hr>`](https://github.com/editor-js/delimiter/issues/27)

### CODE REVIEW

**Comment by Sozialarchiv** [comment]
@GoldenJaden @neSpecc @TatianaFomina

I tested this pr. It works and is very useful. Can someone accept this pr. Thank you very much.

**Review by Sozialarchiv — APPROVED** [review]

**Comment by Sozialarchiv** [comment]
@neSpecc:

Is something missing for this commit. Can I help somehow?

**Review by neSpecc — COMMENTED** [review]
seems ok, please update a patch version

**Comment by Sozialarchiv** [comment]
> seems ok, please update a patch version

It is not my pr. I think I can not change it. 

Should I create a own pr with the changes and a version?

**Review by neSpecc — DISMISSED** [review]

**Review by neSpecc — APPROVED** [review]

**Comment by neSpecc** [comment]
thanks, @gajendrajena and @Sozialarchiv . If you want to continue contributing, let's connect in Telegram: write me directly: https://t.me/specc and we'll discuss what to do next

**Comment by gajendrajena** [comment]
I will connect with you on telegram 
t.me/gajendrajena

**Pull request merged**
